# Generated by Django 2.2.4 on 2023-01-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pie_app', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='pie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voted_pies', to='pie_app.Pypie'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voted_users', to='login_app.User'),
        ),
    ]
