# Generated by Django 2.2.4 on 2023-01-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('pie_app', '0004_auto_20230117_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='pie',
        ),
        migrations.AddField(
            model_name='vote',
            name='pie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_pies', to='pie_app.Pypie'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voted_users', to='login_app.User'),
        ),
    ]
