# Generated by Django 2.2.4 on 2023-01-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('pie_app', '0005_auto_20230117_1911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Vote1',
        ),
    ]
